classe E1 extende Exception {
    super.mensagem = "Erro E1!";    
}

classe E2 extende Exception {}

classe A {
    
    b = novo B();

    func aa( x ) tratar E1 {
        tente {
            retorne b.bb( 1 )+x;
        } capture ( E2 e ) {
            lance novo E1();
        } finalize {
            exibaln "FINALIZOU E RETORNOU!";
        }
    }

}

classe B {

    func bb( x ) tratar E2 {
        se ( x == 1 ) 
            lance novo E2();
        retorne x;
    }

}

a = novo A();

xx = falso;
yy = falso;

tente {
    x = a.aa( 2 );
} capture ( E1 e ) {
    xx = verdade;
} finalize {
    yy = verdade;
}


